
server:
  port: 8001

mybatis:
  type-aliases-package: com.wei.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username : root
    password : root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters : stat
    maxActive : 1000
    initialSize : 100
    maxWait : 60000
    minIdle : 500
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    name: provider-user
eureka:
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: provider-user
    prefer-ip-address: true
info:
  app:
    name: ${spring.application.name}
  build:
    artifactId: ${project.artifactId}
    version: ${project.version}